---
- name: DuckDNS | Update IP
  cron:
    name: "Update DuckDNS IP"
    minute: "*/5"
    job: "echo url=\"https://www.duckdns.org/update?domains={{ DUCKDNS_DOMAIN }}&token={{ DUCKDNS_TOKEN }}&ip=\" | curl -k -K -"