---
- name: Make sure the swag container is created and running
  docker_container:
    name: "swag"
    image: "ghcr.io/linuxserver/swag"
    pull: yes
    networks:
      - name: swag_internal_vlan
    capabilities:
      - net_admin
    state: 'started'
    env:
      "PUID": "{{ GUID }}"
      "PGID": "{{ GUID }}"
      "TZ": "{{ TZ }}"
      "URL": "{{ SWAG_URL }}"
      "SUBDOMAINS": "wildcard"
      "VALIDATION": "duckdns"
      "DUCKDNSTOKEN": "{{ DUCKDNS_TOKEN }}"
    ports:
      - "{{ SWAG_HTTPS_PORT }}:443"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/swag/nginx:/config/nginx"
      - "{{ DOCKER_DATA_DIR }}/swag/dns-conf:/config/dns-conf"
      - "{{ DOCKER_DATA_DIR }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped
