- name: Copy local SSH key to remote host
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  register: ssh_key_config

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  when: ssh_key_config.changed
  register: sshd_passwordless_config
  become: true

- name: Rertart SSH Daemon
  service:
    name: sshd
    state: restarted
  when: sshd_passwordless_config.changed
  become: true