- name: Home server | Pre tasks
  hosts: homeserver
  gather_facts: no
  pre_tasks:
    - include_tasks: tasks/change_ssh_port.yml
      tags: port

- name: Home server | Tasks
  hosts: homeserver
  roles:
    #
    # Dependencies
    - role: dependencies/docker
      tags:
        - dependencies
        - docker

    #
    # System
    - role: system/duckdns
      tags:
        - system
        - duckdns

    - role: system/swag
      tags:
        - system
        - containers
        - swag

    #
    # Services
    - role: services/homer
      tags:
        - containers
        - homer

    - role: services/homeautomation/homeassistant
      tags:
        - containers
        - homeautomation
        - homeassistant