- name: Home server | Pre tasks
  hosts: homeserver
  gather_facts: no
  pre_tasks:
    - include_tasks: tasks/change_ssh_port.yml
      tags: port

- name: Home server | Tasks
  hosts: homeserver
  roles:
    #
    # Dependencies
    - role: dependencies/docker
      tags:
        - dependencies
        - docker

    #
    # Security
    - role: security/ssh
      tags:
        - security
        - ssh

    #
    # System
    - role: system/argoncase
      tags:
        - system
        - argoncase
    
    - role: system/authelia
      tags:
        - system
        - authelia

    - role: system/reboot
      tags:
        - system
        - reboot

    - role: system/duckdns
      tags:
        - system
        - duckdns

    #    - role: system/nginx
    #      tags:
    #        - system
    #        - containers
    #        - nginx

    - role: system/swag
      tags:
        - system
        - containers
        - swag

    #- role: system/traefik
    #  tags:
    #    - system
    #    - containers
    #    - traefik

    - role: system/zsh
      tags:
        - system
        - zsh

    # 
    # Management
    - role: containers/management/heimdall
      tags:
        - containers
        - management
        - heimdall

    #
    # Services - Home automation
    - role: containers/homeautomation/homeassistant
      tags:
        - containers
        - homeautomation
        - homeassistant

    - role: containers/homeautomation/mosquitto
      tags:
        - containers
        - homeautomation
        - mosquitto

    # TODO potentially broken
    - role: containers/homeautomation/zigbee2mqtt
      tags:
        - containers
        - homeautomation
        - zigbee2mqtt
    

    # Watchtower
    - role: containers/watchtower
      tags:
        - containers
        - watchtower


    #
    # Services - Database
    - role: containers/database/mariadb
      tags:
        - containers
        - database
        - mariadb
    
    - role: containers/database/mongodb
      tags:
        - containers
        - database
        - mongodb
    

    #
    # Servers
    - role: containers/servers/recipebook-api
      tags:
        - containers
        - servers
        - recipebook-api

    #
    # Services - Network
    #- role: containers/network/pihole
    #  tags:
    #    - containers
    #    - network
    #    - pihole