- name: Home server | Pre tasks
  hosts: homeserver
  gather_facts: no
  pre_tasks:
    - include_tasks: tasks/change_ssh_port.yml
      tags: port

- name: Home server | Tasks
  hosts: homeserver
  roles:
    #
    # Dependencies
    - role: dependencies/docker
      tags:
        - dependencies
        - docker

    #
    # Security
    - role: security/ssh
      tags:
        - security
        - ssh

    #
    # System
    - role: system/argoncase
      tags:
        - system
        - argoncase

    - role: system/duckdns
      tags:
        - system
        - duckdns

    - role: system/swag
      tags:
        - system
        - containers
        - swag

    - role: system/zsh
      tags:
        - system
        - zsh

    #
    # Services
    - role: containers/homeautomation/homeassistant
      tags:
        - containers
        - homeautomation
        - homeassistant

    - role: containers/homeautomation/mosquitto
      tags:
        - containers
        - homeautomation
        - mosquitto

    - role: containers/homeautomation/zigbee2mqtt
      tags:
        - containers
        - homeautomation
        - zigbee2mqtt