- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
      - "9001:9001"
    pull: yes
    state: 'started'
    volumes:
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/config:/mosquitto/config"
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/log:/mosquitto/log"
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/data:/mosquitto/data"
    restart_policy: unless-stopped