- name: Home assistant | Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "homeassistant/home-assistant:stable"
    networks:
      - name: swag_internal_vlan
    pull: yes
    state: 'started'
    env:
      "TZ": "{{ TZ }}"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/config:/config"
    restart_policy: unless-stopped