- name: Authelia | Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "authelia/authelia"
    pull: yes
    state: 'started'
    networks:
      - name: swag_internal_vlan
        ipv4_address: "172.19.0.3"
    network_mode: bridge
    # env:
    #   "MYSQL_ROOT_PASSWORD": "{{ MARIADB_ROOT_PASSWORD }}"
    #   "MYSQL_DATABASE": "{{ MARIADB_DATABASE }}"
    #   "MYSQL_USER": "{{ MARIADB_USER }}"
    #   "MYSQL_PASSWORD": "{{ MARIADB_PASSWORD }}"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/config:/config"
    ports:
      - "9091:9091"
    restart_policy: unless-stopped