- name: Home assistant | Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "homeassistant/home-assistant:stable"
    network_mode: host
    pull: yes
    state: 'started'
    env:
      "TZ": "{{ TZ }}"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/config:/config"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped