---
- name: "Make sure the {{ container_name }} container is created and running"
  docker_container:
    name: "{{ container_name }}"
    hostname: "{{ container_name }}"
    image: "pihole/pihole:latest"
    pull: true
    state: 'started'
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
    networks:
      - name: nginx_lan
    env:
      TZ: "{{ TZ }}"
      WEBPASSWORD: "{{ VAULT_PIHOLE_PASSWORD }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "{{ PIHOLE_PANEL_PORT }}:80/tcp"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/pihole/etc-pihole:/etc/pihole"
      - "{{ DOCKER_DATA_DIR }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
