- name: test nginx
  command:
    cmd: "docker exec -it swag /usr/sbin/nginx -c /config/nginx/nginx.conf -t"
  register: swag_nginx_test
  changed_when: swag_nginx_test is not search("test is successful")
  failed_when: swag_nginx_test is not search("test is successful")

- name: restart swag
  docker_container:
    name: swag
    state: started
    restart: yes
  when: existing is defined and running is defined
