- name: Maria DB | Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "mariadb:11.1"
    pull: yes
    state: 'started'
    env:
      "MYSQL_ROOT_PASSWORD": "{{ MARIADB_ROOT_PASSWORD }}"
      "MYSQL_DATABASE": "{{ MARIADB_DATABASE }}"
      "MYSQL_USER": "{{ MARIADB_USER }}"
      "MYSQL_PASSWORD": "{{ MARIADB_PASSWORD }}"
    volumes:
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/database:/var/lib/mysql"
      - "{{ DOCKER_DATA_DIR }}/{{ container_name }}/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    restart_policy: unless-stopped